#!/usr/bin/env bash
set -euo pipefail

# This script is intentionally opt-in: it only runs when the user invokes it.
# It never touches the older trumans_scene_v1 output directory.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-$REPO_ROOT/IsaacLab/.venv/bin/python}"
CONFIG="${CONFIG:-$REPO_ROOT/data/yaml_files/trumans_scene_collision_v1.yaml}"
OUTPUT_ROOT="${OUTPUT_ROOT:-$REPO_ROOT/data/motion_for_trackers/trumans_scene_collision_v1}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"

OVERWRITE_FLAG=""
LIMIT_ARGS=()
CLIP_ID_ARGS=()
EXISTING_MOTIONS_ONLY_FLAG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --overwrite)
      OVERWRITE_FLAG="--overwrite"
      shift
      ;;
    --limit)
      if [[ $# -lt 2 ]]; then
        echo "Missing value for --limit" >&2
        exit 2
      fi
      LIMIT_ARGS=(--limit "$2")
      shift 2
      ;;
    --limit=*)
      LIMIT_ARGS=(--limit "${1#*=}")
      shift
      ;;
    --clip-id)
      if [[ $# -lt 2 ]]; then
        echo "Missing value for --clip-id" >&2
        exit 2
      fi
      CLIP_ID_ARGS+=(--clip-id "$2")
      shift 2
      ;;
    --clip-id=*)
      CLIP_ID_ARGS+=(--clip-id "${1#*=}")
      shift
      ;;
    --existing-motions-only)
      EXISTING_MOTIONS_ONLY_FLAG="--existing-motions-only"
      shift
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if [[ -n "${TRUMANS_LIMIT:-}" && ${#LIMIT_ARGS[@]} -eq 0 ]]; then
  LIMIT_ARGS=(--limit "$TRUMANS_LIMIT")
fi

PREP_ARGS=("${LIMIT_ARGS[@]}" "${CLIP_ID_ARGS[@]}")
DATASET_ONLY_ARGS=()
if [[ -n "$EXISTING_MOTIONS_ONLY_FLAG" ]]; then
  DATASET_ONLY_ARGS+=("$EXISTING_MOTIONS_ONLY_FLAG")
fi

cd "$REPO_ROOT"

echo "[1/3] Convert motions, objects, descriptors, and original mesh scene packs"
PYTHONUNBUFFERED=1 "$PYTHON_BIN" data/scripts/prepare_scene_motion_dataset.py \
  "$CONFIG" \
  --stages validate,motions,alignment,objects,descriptors,scene_pack,motion_pack \
  "${PREP_ARGS[@]}" \
  "${DATASET_ONLY_ARGS[@]}" \
  $OVERWRITE_FLAG

echo "[2/3] Build simplified static collision meshes and USD files"
for split in train validation test; do
  mapfile -t COLLISION_SCENE_IDS < <(
    "$PYTHON_BIN" - "$split" "${LIMIT_ARGS[@]}" "${CLIP_ID_ARGS[@]}" <<'PY'
import argparse
import json
import sys
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--limit", type=int, default=None)
parser.add_argument("--clip-id", action="append", default=None)
split = sys.argv[1]
args = parser.parse_args(sys.argv[2:])

repo_root = Path.cwd()
records_path = repo_root / "data/motion_for_trackers/trumans_scene_collision_v1/descriptors" / f"{split}.jsonl"
records = [json.loads(line) for line in records_path.read_text().splitlines() if line.strip()]
if args.clip_id:
    selected = set(args.clip_id)
    records = [record for record in records if record["clip_id"] in selected]
if args.limit is not None:
    records = records[: args.limit]

seen = set()
for record in records:
    scene_id = record["scene_id"]
    if scene_id in seen:
        continue
    seen.add(scene_id)
    print(scene_id)
PY
  )
  for scene_id in "${COLLISION_SCENE_IDS[@]}"; do
    "$PYTHON_BIN" data/scripts/prepare_collision_meshes.py \
      --config "$CONFIG" --split "$split" \
      --scene-id "$scene_id" \
      "${PREP_ARGS[@]}" \
      $OVERWRITE_FLAG
  done
done

echo "[3/3] Replace the static room mesh in each SceneLib pack with collision USD"
for split in train validation test; do
  "$PYTHON_BIN" data/scripts/build_collision_scene_pack.py \
    --config "$CONFIG" --split "$split" \
    "${PREP_ARGS[@]}"
done

echo
echo "Collision-mesh preprocessing complete. Outputs are under:"
echo "  $OUTPUT_ROOT"
echo "  scenes/                 original mesh SceneLib (intermediate)"
echo "  scene_libs/             final collision-mesh SceneLib used for training"
echo "  collision_meshes/       OBJ, USD, pointcloud, and reports per scene"
echo "  mesh contact labels are intentionally not generated by this pipeline"
echo "  motion_libs/             final MotionLib packages"
