#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
DATASET_ROOT="${EGOBODY_DATASET_ROOT:-$REPO_ROOT/data/motion_for_trackers/egobody_smpl_ego_v1/sft_diverse_800_192}"

export EGOBODY_WINDOW_PACK="${EGOBODY_WINDOW_PACK:-$DATASET_ROOT/window_sft_orientation_v1_overfit50}"
export GPC_RLFT_SFT_CHECKPOINT="${GPC_RLFT_SFT_CHECKPOINT:-$REPO_ROOT/results/egobody_gpc_50clip_grounded_dagger_v2/best.ckpt}"
export GPC_RLFT_RUN_NAME="${GPC_RLFT_RUN_NAME:-egobody_gpc_50clip_oracle_residual_v4}"
export GPC_RLFT_ORACLE_TARGET_TOKENS=1
export GPC_RLFT_ACTION_RESIDUAL_MAX_DELTA="${GPC_RLFT_ACTION_RESIDUAL_MAX_DELTA:-0.08}"
export GPC_RLFT_ACTION_RESIDUAL_LOGSTD="${GPC_RLFT_ACTION_RESIDUAL_LOGSTD:--4.0}"
export GPC_RLFT_NUM_ENVS="${GPC_RLFT_NUM_ENVS:-32}"
export GPC_RLFT_ROLLOUT_HORIZON="${GPC_RLFT_ROLLOUT_HORIZON:-32}"
export GPC_RLFT_WINDOW_SIZE="${GPC_RLFT_WINDOW_SIZE:-32}"
export GPC_RLFT_BATCH_SIZE="${GPC_RLFT_BATCH_SIZE:-256}"
export GPC_RLFT_MAX_ITERATIONS="${GPC_RLFT_MAX_ITERATIONS:-500}"
export GPC_RLFT_EVAL_EVERY="${GPC_RLFT_EVAL_EVERY:-25}"
export GPC_RLFT_SAVE_EVERY="${GPC_RLFT_SAVE_EVERY:-25}"
export GPC_RLFT_ACTOR_LR="${GPC_RLFT_ACTOR_LR:-1e-4}"
export GPC_RLFT_PARAMETER_EMA_DECAY="${GPC_RLFT_PARAMETER_EMA_DECAY:-0.995}"
export GPC_RLFT_ACTION_SMOOTHNESS_WEIGHT="${GPC_RLFT_ACTION_SMOOTHNESS_WEIGHT:--0.003}"
export GPC_RLFT_ACTION_ACCELERATION_WEIGHT="${GPC_RLFT_ACTION_ACCELERATION_WEIGHT:--0.01}"
export GPC_RLFT_BODY_LINEAR_JERK_WEIGHT="${GPC_RLFT_BODY_LINEAR_JERK_WEIGHT:--0.02}"
export GPC_RLFT_TRACKING_THRESHOLD_VIOLATION_WEIGHT="${GPC_RLFT_TRACKING_THRESHOLD_VIOLATION_WEIGHT:--0.10}"
export GPC_RLFT_HEAD_ORIENTATION_WEIGHT="${GPC_RLFT_HEAD_ORIENTATION_WEIGHT:-0.22}"

exec "$SCRIPT_DIR/train_egobody_gpc_rlft.sh" "$@"
